/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2a;

/**
 *
 * @author KAMINATOR
 */
public class MenuIngreso extends javax.swing.JFrame {

    /**
     * Creates new form MenuIngreso
     */
    public MenuIngreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btningresoemp = new javax.swing.JButton();
        btningresodep = new javax.swing.JButton();
        btningresoUsuario = new javax.swing.JButton();
        btningresoCon = new javax.swing.JButton();
        btningresoDetalleNomina = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btningresopuesto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingreso de Datos");

        btningresoemp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresoemp.setText("Empleados");
        btningresoemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresoempActionPerformed(evt);
            }
        });

        btningresodep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresodep.setText("Departamento");
        btningresodep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresodepActionPerformed(evt);
            }
        });

        btningresoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresoUsuario.setText("Nuevo Usuario");
        btningresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresoUsuarioActionPerformed(evt);
            }
        });

        btningresoCon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresoCon.setText("Concepto");
        btningresoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresoConActionPerformed(evt);
            }
        });

        btningresoDetalleNomina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresoDetalleNomina.setText("Detalle de Nomina");
        btningresoDetalleNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresoDetalleNominaActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNuevo.setText("Nueva Nomina");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btningresopuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresopuesto.setText("Puesto");
        btningresopuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresopuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btningresoemp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btningresodep, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btningresopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btningresoDetalleNomina, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btningresoCon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btningresoUsuario))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btningresoemp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningresoDetalleNomina)
                    .addComponent(btningresopuesto))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningresodep)
                    .addComponent(btningresoCon))
                .addGap(31, 31, 31)
                .addComponent(btningresoUsuario)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresopuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresopuestoActionPerformed
       new IngresoPuesto().setVisible(true);
    }//GEN-LAST:event_btningresopuestoActionPerformed

    private void btningresodepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresodepActionPerformed
         new IngresoDepartamento().setVisible(true);
    }//GEN-LAST:event_btningresodepActionPerformed

    private void btningresoempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresoempActionPerformed
        new IngresoEmpleados().setVisible(true);
    }//GEN-LAST:event_btningresoempActionPerformed

    private void btningresoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresoConActionPerformed
      new IngresoConcepto().setVisible(true);
    }//GEN-LAST:event_btningresoConActionPerformed

    private void btningresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresoUsuarioActionPerformed
          new IngresarUsuario().setVisible(true);    
    }//GEN-LAST:event_btningresoUsuarioActionPerformed

    private void btningresoDetalleNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresoDetalleNominaActionPerformed
        new IngresoNominaDetalle().setVisible(true);
    }//GEN-LAST:event_btningresoDetalleNominaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        new IngresoNuevaNomina().setVisible(true);

    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btningresoCon;
    private javax.swing.JButton btningresoDetalleNomina;
    private javax.swing.JButton btningresoUsuario;
    private javax.swing.JButton btningresodep;
    private javax.swing.JButton btningresoemp;
    private javax.swing.JButton btningresopuesto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
